Add support for bazel on OSX (#51)
This allows building spectator-cpp on OSX using bazel. Useful for
projects that depends on this library using that build system.

It can be added as a dependency using something like:

```
http_archive(
      name = "spectator",
      urls = ["https://github.com/Netflix/spectator-cpp/archive/v0.7.6.tar.gz"],
      sha256 = "b064f520ab61102f2f6bc82b4a89de735393d0c679d2ac1cd142602d60ee16da",
      strip_prefix = "spectator-cpp-0.7.6"
  )
```

Previously it would fail due to the c-ares dependency having a
hard-coded config for linux. On OSX there is no `MSG_NOSIGNAL`
identifier, which causes the c-ares build to fail with:

```
external/com_github_c_ares_c_ares/ares_process.c:199:10: error: use of undeclared identifier 'MSG_NOSIGNAL'
  return swrite(s, data, len);
         ^
external/com_github_c_ares_c_ares/setup_once.h:204:54: note: expanded from macro 'swrite'
                                    (SEND_TYPE_ARG4)(SEND_4TH_ARG))
                                                     ^
external/com_github_c_ares_c_ares/setup_once.h:126:22: note: expanded from macro 'SEND_4TH_ARG'
                     ^
```

This patch also includes the config for Windows which would make it
possible to build spectator-cpp on that platform (but that is untested
and unsupported)